name: Build and Deploy .NET Framework - Debug to Staging
# Only an example, therefore pushing diretctly to production from master.

on:
  pull_request:
    branches: master
env:
  WEB_APP_NAME: CSVtoJSON        # Replace with your app name
  SOLUTION_FILE_NAME: CSVtoJSON  # Replace with your Solution name
  PROJECT_FILE_NAME: CSVtoJSON   # Replace with your Project name

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master  
    
    # Install Nuget and run Nuget restore
    - name: NuGet Restore
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: '5.3.1'
    - run: nuget restore
    
    # Finds and adds MSBuild to the path
    - name: Setup MSBuild.exe 
      uses: warrenbuckley/Setup-MSBuild@v1

    # Run a build of the solution file with the specified configuration (Debug in this example)
    - name: Run MSBuild
      run: msbuild .\${{env.SOLUTION_FILE_NAME}}.sln /p:Configuration=Debug /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:PackageLocation="\temp\package.zip"
       
    # Deploying the package assuming your project and solution are named the same
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: ${{env.WEB_APP_NAME}} 
        publish-profile: ${{ secrets.azureWebAppPublishProfileStaging }} # Define secret variable in repository settings as per action documentation
        #package: '${{env.PROJECT_FILE_NAME}}/' 
        package: '\temp\package.zip'
